import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import type { Metadata } from "next";

import { poppins } from "@/utils/font";
import Providers from "@/components/Providers";


export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Providers>
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
