import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Country",
  description: "Generated by create next app",
};

export default function SpesificCountryLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children
}
